<link href='http://fonts.googleapis.com/css?family=New+Rocker' rel='stylesheet' type='text/css'>
<h1 style="font-family: 'New Rocker';font" ><?php echo $this->title; ?> </h1>
<br>
<form action="/application/bandas/save" method="post" role="form" class="form-horizontal">

	<div class="form-group">
		<label style="font-family: 'New Rocker';" class="col-sm-2 control-label" for="nome_banda">
			<?php echo $this->form->get('nome_banda')->getOptions()["label"]; ?>
		</label>
		<div class="col-sm-4">
			<input class="form-control" type="text" name="nome_banda" id="nome_banda" title="Insira o título do post." data-error-message="Título obrigatório" value="<?php if(isset($form)) echo $post->nome_banda; ?>"/>
		</div>
	</div>
	<div class="form-group">
		<label style="font-family: 'New Rocker';" class="col-sm-2 control-label" for="desc_banda">
			<?php echo $this->form->get('desc_banda')->getOptions()["label"]; ?>
		</label>
		<div class="col-sm-4" >
			<textarea style="font-family: 'New Rocker';" class="form-control" name="desc_banda" id="desc_banda" data-error-message="Texto obrigatório">
				<?php if(isset($form)) echo $form->desc_banda; ?>
			</textarea>
		</div>
	</div>
	<div class="form-group">
		<label style="font-family: 'New Rocker';" class="col-sm-2 control-label" for="num_integrantes_banda">
			<?php echo $this->form->get('num_integrantes_banda')->getOptions()["label"]; ?>
		</label>
		<div class="col-sm-4" >
			<select style="font-family: 'New Rocker';" class="form-control" type="select" name="num_integrantes_banda" id="num_integrantes_banda" data-error-message="Texto obrigatório">
				<?php if(isset($form)) echo $form->num_integrantes_banda; ?>
				<option>Quantos são?</option>     	
				<option>1</option><option>2</option><option>3</option><option>4</option>
				<option>5</option><option>6</option><option>7</option><option>8</option>
				<option>9</option><option>10</option>
			</select>
		</div>
	</div>
	<div style="font-family: 'New Rocker';" class="actions clearfix">
		<input style="background:#000000; color:#FFFFFF;" name="submit" type="submit" class="btn btn-lg" id="submitbutton" value="Salvar" title="Salvar" />
		<input  style="background:#999999; color:#FFFFFF" name="cancel" type="submit" class="btn btn-lg" value="Cancelar" title="Cancelar" />
	</div>
</form>
